JobBoard/Models/Job.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace JobBoard.Models
{
    public class Job
    {
        [Key]
        [Display(Name = "Job ID")]
        public int job { get; set; }
        
        [Display(Name = "Job Title")]
        [Required(ErrorMessage = "Job Title is required")]
        public string jobTitle { get; set; }

        [Display(Name = "Description")]        
        public string description { get; set; }

        [Display(Name = "Created At")]
        [Required(ErrorMessage = "Created At is required")]
        public DateTime createdAt { get; set; }

        [Display(Name = "Expires At")]
        [Required(ErrorMessage = "Expires At is required")]
        public DateTime expiresAt { get; set; }
    }
}

JobBoard/Models/ModelContext.cs
using System;
using System.Data.Entity;
using System.Linq;

namespace JobBoard.Models
{
    public class ModelContext : DbContext
    {        
        public ModelContext()
            : base("ModelContext")
        {
        }
        public DbSet<Job> Jobs { get; set; }
    }       
}

JobBoard/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobBoard.Models;

namespace JobBoard.Controllers
{
    public class JobsController : Controller
    {
        private ModelContext db = new ModelContext();

        // GET: Jobs
        public ActionResult Index()
        {
            return View(db.Jobs.ToList());
        }

        // GET: Jobs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // GET: Jobs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Jobs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "job,jobTitle,description,createdAt,expiresAt")] Job job)
        {
            if (ModelState.IsValid)
            {
                db.Jobs.Add(job);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(job);
        }

        // GET: Jobs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: Jobs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, [Bind(Include = "job,jobTitle,description,createdAt,expiresAt")] Job job)        
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (ModelState.IsValid)
            {
                job.job = id.Value;
                db.Entry(job).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(job);
        }

        // GET: Jobs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Job job = db.Jobs.Find(id);
            db.Jobs.Remove(job);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobBoard/Views/Jobs/Create.cshtml
@model JobBoard.Models.Job

@{
    ViewBag.Title = "New Job";
}

<h1 class="text-center">New Job</h1>

<div class="card">
    <div class="card-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            
            <div class="form-group row">
                @Html.LabelFor(model => model.jobTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.jobTitle, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.jobTitle, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row d-none">
                @Html.LabelFor(model => model.createdAt, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10 input-group date" id='dtpCreatedAt'>
                    @Html.TextBoxFor(model => model.createdAt, htmlAttributes: new { @class = "form-control bg-white", type = "text", @readonly = "readonly" })
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-calendar-alt"></i></span>
                    </div>
                    @Html.ValidationMessageFor(model => model.createdAt, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.expiresAt, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10 input-group date" id='dtpExpiresAt'>
                    @Html.TextBoxFor(model => model.expiresAt, htmlAttributes: new { @class = "form-control bg-white", type = "text", @readonly = "readonly" })
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-calendar-alt"></i></span>
                    </div>
                    @Html.ValidationMessageFor(model => model.expiresAt, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="col-md-offset-2 col-md-10 text-center">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a href="@Url.Action("Index","Jobs")" class="btn btn-secondary">Cancel</a>
            </div>
        }
    </div>
</div>

@section Scripts {

    <script type="text/javascript">

        $('#dtpCreatedAt').datetimepicker({
            format: 'DD/MM/YYYY',
            ignoreReadonly: true,
            defaultDate: new Date(),
        });

        $('#dtpExpiresAt').datetimepicker({
            format: 'DD/MM/YYYY',
            ignoreReadonly: true,
            defaultDate: new Date(),
        });

    </script>
}

JobBoard/Views/Jobs/Delete.cshtml
@model JobBoard.Models.Job

@{
    ViewBag.Title = "Job Delete";
}

<h1 class="text-center">Job Delete</h1>

<h4>Are you sure you want to delete this?</h4>

<div class="card">  
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.job)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.job)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.jobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.jobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.createdAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.createdAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.expiresAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.expiresAt)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <div class="col-md-offset-2 col-md-10 text-center">
                <input type="submit" value="Delete" class="btn btn-danger" />
                <a href="@Url.Action("Index","Jobs")" class="btn btn-secondary">Cancel</a>
            </div>
        </div>
    }
</div>

JobBoard/Views/Jobs/Details.cshtml
@model JobBoard.Models.Job

@{
    ViewBag.Title = "Job Details";
}

<h1 class="text-center">Job Details</h1>

<div class="card">
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.job)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.job)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.jobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.jobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.createdAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.createdAt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.expiresAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.expiresAt)
        </dd>

    </dl>

    <div class="col-md-offset-2 col-md-10 text-center">
        <a class="btn btn btn-warning" href="@Url.Action("Edit", "Jobs", new { id = Model.job })">Edit</a>
        <a class="btn btn btn-secondary" href="@Url.Action("Index", "Jobs")">Back</a>
    </div>

</div>

JobBoard/Views/Jobs/Edit.cshtml
@model JobBoard.Models.Job

@{
    ViewBag.Title = "Edit Job";
}

<h1 class="text-center">Edit Job</h1>

<div class="card">
    <div class="card-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.Hidden("id", Model.job)

            <div class="form-group row">
                @Html.LabelFor(model => model.jobTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.jobTitle, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.jobTitle, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row d-none">
                @Html.LabelFor(model => model.createdAt, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10 input-group date" id='dtpCreatedAt'>
                    @Html.TextBoxFor(model => model.createdAt, htmlAttributes: new { @class = "form-control bg-white", type = "text", @readonly = "readonly" })
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-calendar-alt"></i></span>
                    </div>
                    @Html.ValidationMessageFor(model => model.createdAt, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.expiresAt, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10 input-group date" id='dtpExpiresAt'>
                    @Html.TextBoxFor(model => model.expiresAt, htmlAttributes: new { @class = "form-control bg-white", type = "text", @readonly = "readonly" })
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fas fa-calendar-alt"></i></span>
                    </div>
                    @Html.ValidationMessageFor(model => model.expiresAt, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="col-md-offset-2 col-md-10 text-center">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a href="@Url.Action("Index","Jobs")" class="btn btn-secondary">Cancel</a>
            </div>

        }
    </div>
</div>

@section Scripts {

    <script type="text/javascript">

        $('#dtpCreatedAt').datetimepicker({
            format: 'DD/MM/YYYY',
            ignoreReadonly: true,
            defaultDate: new Date(),
        });

        $('#dtpExpiresAt').datetimepicker({
            format: 'DD/MM/YYYY',
            ignoreReadonly: true,
            defaultDate: new Date(),
        });

    </script>
}

JobBoard/Views/Jobs/Index.cshtml
@model IEnumerable<JobBoard.Models.Job>

@{
    ViewBag.Title = "Jobs";
}

<h1 class="text-center">Jobs</h1>

<nav class="navbar navbar-expand navbar-light bg-light mb-3">
    <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Create","Jobs")">
                    <i class="far fa-plus-square"></i> New
                </a>
            </li>           
        </ul>
    </div>
</nav>

<div class="card">
    <table class="table" id="jobList">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.job)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.jobTitle)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.createdAt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.expiresAt)
                </th>
                @if (Model.Count() > 0)
                {
                    <th></th>
                }
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() == 0)
            {
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            }
            else
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.job)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.jobTitle)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.description)
                        </td>
                        <td>
                            @item.createdAt.ToShortDateString()
                        </td>
                        <td>
                            @item.expiresAt.ToShortDateString()
                        </td>
                        <td>
                            <a class="btn btn-info" href="@Url.Action("Details", "Jobs", new { id = item.job })" data-toggle="tooltip" title="Details">
                                <i class="far fa-list-alt"></i>
                            </a>
                            <a class="btn btn-warning" href="@Url.Action("Edit", "Jobs", new { id = item.job })" data-toggle="tooltip" title="Edit">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a class="btn btn-danger" href="@Url.Action("Delete", "Jobs", new { id = item.job })" data-toggle="tooltip" title="Delete">
                                <i class="fas fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            const options = {
                "searching": false,
                "ordering": false,                
            }
            $('#jobList').DataTable(options);
        });
    </script>
}

JobBoard/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css" />
    <link rel="stylesheet" href="~/Resources/bootstrap-datetimepicker.css">
    <link rel="stylesheet" href="~/Resources/custom.css">

    <title>@ViewBag.Title - Job Board</title>
</head>
<body class="d-flex flex-column h-100">

    <main role="main" class="flex-shrink-0">
        @Html.Partial("_navbar")
        <div class="container">
            @RenderBody()
        </div>
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js" type="text/javascript"></script>
    <script src="~/Scripts/moment.js" type="text/javascript"></script>
    <script src="~/Scripts/bootstrap-datetimepicker.js" type="text/javascript"></script>
    <script type="text/javascript">
        $('[data-toggle="popover"]').popover();
        $('[data-toggle="tooltip"]').tooltip();
    </script>
    @RenderSection("scripts", required: false)

</body>
</html>

JobBoard/Views/Shared/_navbar.cshtml
<nav class="navbar navbar-dark bg-primary fixed-top">
    <a class="navbar-brand" href="@Url.Action("Index", "Home")"><strong>Job Board</strong></a>
</nav>